### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by altendky**
https://ci.appveyor.com/project/KyleAltendorf/pytest-twisted

### CODE REVIEW

**Comment by nicoddemus** [comment]
Awesome, thanks for this!

FWIW in my experience the `appveyor.yml` file, because `tox` will take care of creating virtual envs an using the correct Python version for each, can be much simpler. For example, pytest's own `appveyor`:

https://github.com/pytest-dev/pytest/blob/master/appveyor.yml#L1-L44

**Comment by vtitor** [comment]
Awesome, thanks.

**Comment by altendky** [comment]
@nicoddemus That doesn't cover both 32 and 64 bit, correct?  I'm guessing it's 32-bit only since the special virtualenv I upgrade to is required for 64-bit to work fully (at least with Qt stuff, though not everything uses `python3.dll`).  Is it important to cover both?  I don't know...  but I've been doing it.  Then again, I don't on Travis.  :|

**Comment by nicoddemus** [comment]
> That doesn't cover both 32 and 64 bit, correct?

You are right it doesn't, I did not realize that. 👍

**Pull request merged**
