### PR TITLE
[30] Test and claim Python 3.7 support

### PR DESCRIPTION
**Pull request by altendky**
#30

### CODE REVIEW

**Comment by altendky** [comment]
[WIP] due to the use of Twisted from Git, if nothing else.  They are one test/deprecation away from passing all tests on 3.7.

**Comment by JapieBosch** [comment]
Hi 

So I'm very new to git and github, and I was just wondering what is going on here. From what I can tell, is that you worked on some files to make the module compatible with python 3.7. And are now waiting for someone to accept these changes to integrate it with the module and include it in the next release. Am I correct? If not will you please help me understand what is going on?

**Comment by altendky** [comment]
Roughly yes.  In the details I didn't have to change code per-se, I just enabled testing against 3.7 and add the 3.7 classifier for PyPI metadata.  I could actually merge this myself but this is still a way to get a build of this to make sure it really works without committing it to the main branch.

For more info: https://help.github.com/articles/about-pull-requests/

**Comment by gardenunez** [comment]
Hi @altendky, is this issue blocked for any reason or do you think it will be merge and release soon? Need any help on it?

**Comment by altendky** [comment]
@gardenunez thanks for the reminder.  Twisted 18.9.0 with 3.7 support was just released.  I think this is ready.  @vtitor, care to review and merge?

I could technically merge this myself but I don't know the release process, but, @gardenunez do note that there was no actual code change here, just testing against Python 3.7 to make sure it worked and reporting support via the PyPI classifiers.  This particular PR won't do anything directly for users.

**Comment by gardenunez** [comment]
Hi @altendky,  you are totally right and I can install pytest-twisted for Python3.7 at the moment. Thanks.

**Comment by vtitor** [comment]
Great work @altendky, thanks a lot. I will review your pull requests (#34, #37, ..) as soon as possible.

**Pull request merged**
