### PR TITLE
Test x32 on Windows

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by cdunklau** [comment]
but... why? What problems can you imagine that would result from different bitness?

**Comment by altendky** [comment]
Quite the opposite... Why am I not also adding matrixing against virtualenv and venv?  Historically I regularly had issues with pyqt against only some of these combinations. Though maybe there's an argument that that isn't for us to find. Or, it's easy so let's go for it.

IIRC, it was stuff like virtualenv forgetting to copy/link the python3.dll and most stuff doesn't use the stable ABI or something so you won't notice with most packages etc.

Maybe it's not that valuable but I'm not clear there's a big downside given that there is 'real' matrix generation available.  Or maybe I'm being greedy with the pytest gha time.

**Comment by cdunklau** [comment]
Yeah all that sounds like "not our problem"... as it is we're being nice by testing against various reactors and OS.

I won't stop you, but I won't approve this either :)

**Comment by altendky** [comment]
Isn't testing against what we claim to implement support for kind of a core responsibility and not a favor?  (The reactors and operating systems)

But yeah, I think I can be talked out of being responsible for identifying PyQt5+virtualenv incompatibilities that would manifest without us.  We don't do anything specific that is likely to care about 32 vs. 64 so not a big risk.  If we were an application package (where I did this first, maybe?) it might be a different matter.

**Comment by cdunklau** [comment]
> Isn't testing against what we claim to implement support for kind of a core responsibility and not a favor?

Of course it is. I was being somewhat hyperbolic :)

**Pull request closed without merging**
